[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
libreplex_editions = "bYSF2fxhcUjvqapf1c9VYmykH8CpySMPvCvxgFkfSSW"
libreplex_editions_controls = "5NeY3NR3ZT8D6ck9NrgBBsJjiH25cL4mmksF1x5ZrHwW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "usb://ledger"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 test/tests/**/*.ts"

[test]
startup_wait = 100000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[[test.validator.clone]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"

[[test.validator.clone]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "5hx15GaPPqsYA61v6QpcGPpo125v7rfvEfZQ4dJErG5V"
