[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
libreplex_creator = "78deTr7qycJ6498vSd3pNMhdCKKWxMipniitVHQcM8RM"
libreplex_creator_controls = "G9whLiLT9nSkxwWzWvbiKKrTL6yWxvzh2UXqNht5VXqV"
libreplex_default_renderer = "8MzCUXH5Y52jjorkSu9G6Y69AHBwFoW8GC7MFFhDJRaZ"
libreplex_editions = "2wxjzcyejdC7jqgJPx3SVGhtroKoyB7ixERtRhKXTBxR"
libreplex_editions_controls = "GoD9GkAZuP9Cc2DUbvv6CNXSz1cG4FMxzRxLoB37WEKy"
libreplex_inscriptions = "GAc6iGWe4D8ZDT3xqJXysn3wfARrpz9eLUC1jquvd3Q1"
libreplex_legacy_inscribers = "Leg1xVbrpq5gY6mprak3Ud4q4mBwcJi5C9ZruYjWv7n"
libreplex_metadata = "LibrQsXf9V1DmTtJLkEghoaF1kjJcAzWiEGoJn8mz7p"
libreplex_monoswap_deprecated = "3nY7oDsfv8UwRiE6rUE5abb3g3gLZKcmTHbQrsed6SrQ"
libreplex_nft = "3oR36M1JQ9LHM1xykKTHDvhuYVM5mDAqRmq989zc1Pzi"
libreplex_shop = "ListjawGEdhxuAErSyYwcTEGWQswFoi6FScnGG1RKSB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 js-tests/**/*.ts"

[test]
startup_wait = 100000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[[test.validator.clone]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"

[[test.validator.clone]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
