export const EDITIONS_PROGRAM_ID =
  'GWvPUJ7j4XzT1AJnHn7UkmJbodRkvCay2yLwVQcN2YEp';
export const EDITIONS_CONTROLS_PROGRAM_ID =
  '8FEBY2DomLgXkBU8Le4eYRUSTxTh2AeSubvmVV6dxnco';
export const TOKEN_GROUP_EXTENSION_PROGRAM_ID =
  '5hx15GaPPqsYA61v6QpcGPpo125v7rfvEfZQ4dJErG5V';
